

const message[10] = "Hello world!\n" : string;
var i=2, j=1 : number;
const i=4.2e1, j=0.420E+2: number;
var s1[10]="Hello world!\n", s2: string;

var i, j = 10.5: number;
var s1, s2: string;
var n1[10]: number;
var x = 3.5, y: number;
var s[10] = "hello", ss: string;
var test = false: boolean;
const pi = 3.14: number;

function readString(): string ;
function readNumber(): number ;
function writeString(s: string);

 
function start(): void {
  
  return;
}

